# Site settings
# Enter your own credentials here
title: "Molecular Dynamics of Polyethylene Crystallization"
email: alohse3@gatech.edu
# Need repo and pages description: repo-stores much of the content of the project
# pages - is a subset of the repo showing what you want
description: >
  Crystal orientation of polymer molecular dynamics simulations are investigated. Of importance are the density and Herman's orientation with respect to the tensile axis. Changes in orientation with time as data has simulated tensile test applied to them allow us to develop structure-property linkages for polyethylene.
baseurl: "/MIC-Polymer-MD-Simulations" # replace ``/research-pages`` with the name of the parents repository
url: "Materials-Informatics-Lab.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: PEMDsimulations

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: alohse
  repo: MIC-Polymer-MD-Simulations
  # Branch hosting Github pages
  branch: gh-pages
